### ISSUE TITLE
Captain Pillager not spawning

### ISSUE THREAD

**Issue by Efendiminati** [dzwdz/chat_heads#106]
Is there a chance that chat heads interve captain pillager's spawning? I was looking for this issue on reddit and the guy having the same problem said solved this by deleting chat heads and it seems its true, captain pillagers do not spawn with this mod on

**Comment by Fourmisain** [comment]
I don't see how that would be possible, being a client-side mod and all, but you never know, so here's my results:

Using spawn eggs:
![spawnegg](https://github.com/user-attachments/assets/c05d928b-035c-442d-a1b5-649ad88b9ddf)

Force-spawned patrols (by modifying the game's patrol timer from 5 1/2 days to 0 ticks):
![forcespawn](https://github.com/user-attachments/assets/185a2f0d-699f-49cc-a2b2-f6f6420dd1c6)

That is in Fabric 1.21.

To be honest, this sounds like someone convinced themselves there's an issue, removed a mod and then convinced themselves that that was the solution, when everything was intact the entire time.

Captains are _rare_ - regular Pillager spawns only have a 6% chance to be a captain.

Patrols also only spawn every 5 1/2 ingame days, with a chance of only 1 in 5 - so realistically it's more like every 27 1/2 days - and even then they could just not spawn due to missing spawn conditions (block light level ≤ 8, not being near a village, etc).

Afaik Raids have guaranteed Captain spawns, so if you wanna do some testing, start a raid:
![raid](https://github.com/user-attachments/assets/72feecc2-5ad5-4f2e-b8e7-d55b196c8c1d)

**Comment by Efendiminati** [comment]
Ah, thank you for looking into it and sorry for inconvenience.

**Comment by Fourmisain** [comment]
No problem!

Just one last thing:
It _is_ possible that such an issue is caused by two conflicting mods and that deactivating a random mod (temporarily) fixes it.
This got to do with the load order of mods - some order may work fine, another may cause the issue.

That said, I still find it very unlikely that there actually are two mods specifically modifying the game's captain logic.

Assuming the issue is real, the only thing I could think of is mods that change/lengthen the time of day.
If e.g. the day is 3x as long, this may also increase the (already long an random) time between patrol spawns 3-fold.
