### ISSUE TITLE
Incompatibility with Emojiful

### ISSUE THREAD

**Issue by LoboMetalurgico** [dzwdz/chat_heads#119]
When Emojiful is installed, the heads doesn't render

**Comment by Fourmisain** [comment]
They do when using "Before Line" rendering.
This is yet another incompatibility like with Caxton #114 and ModernUI #116 where the vanilla text rendering is being replaced (note that none of the 3 mods are compatible between each other).
This time though it looks potentially solvable as Emojiful is close to vanilla rendering.

...

Yeah, I got it!
For 1.21.1 at least.
Had to restructure the cross-platform stuff - thank goodness for [`@ExpectPlatform`](https://docs.architectury.dev/plugin/expect_platform), would have been ugly as heck otherwise.

I don't expect the same code to work for 1.20.1 (Emojiful 4.2.0) and earlier, but I'll try backporting and see what happens.

**Comment by Fourmisain** [comment]
> I don't expect the same code to work for 1.20.1 (Emojiful 4.2.0) and earlier

It did!
Well, almost, but no big changes were needed.

Anyway, new versions are out!

**Comment by LoboMetalurgico** [comment]
Thank you!!
