### ISSUE TITLE
Chat Heads required on server?

### ISSUE THREAD

**Issue by cpm9** [dzwdz/chat_heads#16]
When using a Forge server the forge version of the mod (chat_heads_forge-0.2.0.jar) is set up to be required on the server is this intended?

From client latest.log file:
_[11Nov2021 22:21:38.541] [Netty Client IO #0/INFO] [net.minecraftforge.fml.client.ClientHooks/CLIENTHOOKS]: Client has mods that are missing on server: [chat_heads]_

It also makes a red X appear in the clients multiplayer menu screen which is confusing to some users
![image](https://user-images.githubusercontent.com/82549089/141414803-0cdd4189-8f88-4084-9d09-db872a825dae.png)

**Comment by Fourmisain** [comment]
That's not intended, as it's supposed to be a client-only mod.

I managed to fix this just now for version 0.5.0 but since you're using 0.2.0 it looks like I have to do a backport.

**Comment by Fourmisain** [comment]
Argh, I thought I was done backporting in just 5 minutes till it turned out to crash on load.
I thought Architectury had broken refmap generation because it worked in the devenv and an hour later I realized I was actually running Minecraft 1.16, not 1.16.5 the whole time!

And just to rub some more salt in the wound the Forge version then started to _sometimes_ fail running the client code - because I accidentally put a second `@Mod` annotation on another class.

I want my time back! 😆

Anyway, new versions are up and approved!

**Comment by cpm9** [comment]
thanks youre awesome!
