### ISSUE TITLE
TLauncher Accounts don't show their heads in chat and the heads become gray [Bug/ for TLauncher Accounts]

### ISSUE THREAD

**Issue by JamTheAdventurer** [dzwdz/chat_heads#21]
Im Using this in my ModPack and the heads in chat would become gray, Only people who had Default skin's heads would only work.

Details:
MC Version: 1.16.5
ModLoder Version: 36.2.4
Mod Version: [0.5.1](https://www.curseforge.com/minecraft/mc-mods/chat-heads/files/3523331)
ModLoader: Forge

**Comment by Fourmisain** [comment]
Okay, just on the off chance you don't know any better:

Don't use TLauncher.
It's a cracked client and completely illegal - they redistribute Minecraft for free while putting ads on it and they even have a subscription model to get rid of them again which is beyond scummy.

They claim "you get a perfectly clean Minecraft" with unmodified files, but they also have a "unique skin system" and "premium accounts" - do you see the contradiction?

Since their launcher is completely closed source, there's no way of knowing what it's _actually_ doing.

That skin system they have is clearly what's breaking things with this mod and unless you can prove this happens with the vanilla launcher, there is no way I'm even gonna try and fix this.

Minecraft is a game you put hundreds or thousands of hours in, it's $27, don't be cheap and buy the actual game.
Or wish for it for christmas, that's not too far off from today.
