### ISSUE TITLE
Chat heads isnt working on feather

### ISSUE THREAD

**Issue by MasterlinkYT** [dzwdz/chat_heads#31]
Idk if im doing something wrong but it isnt working when i  try to use it on feather 1.19 or feather in general. Im using fabric

**Comment by Fourmisain** [comment]
First time I heard about Feather client and I'm not pleased with what I read about it.
They are known to have stolen code (from Patcher and Sodium) and of course the client is closed source and monetized (via "Cloaks", which are totally not capes) too because why wouldn't it be...
Their [privacy policy](https://feathermc.com/privacy/) doesn't look any better either. They admit to collect your IP, personally identifiable information, all mods you use, all servers you join, when logging in via Discord, they even take your friends list!
You can read more about it e.g. [here](https://hypixel.net/threads/feather-client-what-you-should-know-about-this-client.4801748/), there's tons of videos about it too (under the first hits when googling "feather client").

I can only repeat my stance on those kinds of launchers/clients:
It's closed source, so we can't fix the issue.
It's scummy, so we _won't_ fix the issue.

If you're modding your game anyway, just [install Fabric](https://fabricmc.net/use/installer/) on the vanilla launcher or maybe MultiMC and add all the mods you want to make your own "client", there's no need for all that baggage.
