### ISSUE TITLE
Name aliases

### ISSUE THREAD

**Issue by Poly2it** [dzwdz/chat_heads#34]
Many servers allow users to create nicknames for themselves (like `~Poly`), but these do not register by this mod. Would it be possible to allow users to define aliases for player names in the mod config?

**Comment by Fourmisain** [comment]
Do these nicknames show in the player list when pressing tab or is this purely in the messages that get sent?
If it's the former, this sounds like a bug or an issue with Chat Heads' settings which "Heuristic only" sender detection could fix.
If it's the latter, we probably need something like aliases like you suggest.

**Comment by Poly2it** [comment]
![Screenshot from 2023-01-02 14-36-21](https://user-images.githubusercontent.com/84731064/210238679-6ec44abd-154e-481a-b144-bba20bc8cd72.png)

Here is a scenario on a server which does not provide sender UUIDs.  
BUSHI_YAMMAMOTO is nicknamed as ~Yamamoto, but their skin does not show up in chat with heuristic detection.  
.Owlet1124 is a bedrock player logged on through [GeyserMC](https://github.com/GeyserMC/Geyser), but their skin is available to the client as show in the image. Their nickname is ~Owl.

**Comment by Fourmisain** [comment]
k, in this case I think I can push my branch - already wrote an implementation last week.

I still find it so weird that they made nicknames separate from display and profile names - display names are the "vanilla" way to nickname players (vanilla itself doesn't directly use that functionality; they literally made it so that modded servers could rename players), but oh well.

Oh right, I only wrote the implementation for 1.19.3, is that fine or do you need a backport?

**Comment by Poly2it** [comment]
Nice work!
I have not had the opportunity to update to 1.19.3 yet as not all mods I depend on have released for the version yet, so I am still on 1.19.2. A back-port would be very kind.

**Comment by Fourmisain** [comment]
k, backport to 1.19.2 / 1.19.1 is up!
Well, kinda, Modrinth seems to have technical trouble right now.

If anyone reads this and wants a backport for earlier versions, just ask!
