### ISSUE TITLE
not working with skin changer

### ISSUE THREAD

**Issue by rikzun** [dzwdz/chat_heads#36]
mod doesn't work with another mod that adds skins to minecraft with online mod disabled
link https://www.curseforge.com/minecraft/mc-mods/skinchanger

**Comment by Fourmisain** [comment]
This looks like an issue with older versions of Skin Changer (and also [OfflineSkins](https://www.curseforge.com/minecraft/mc-mods/offlineskins), the mods seem to share code), specifically for Minecraft 1.16 and I don't think Chat Heads can be easily changed to accomodate for that.

On newer versions, both mods ASM-patch `PlayerInfo.getSkinLocation()` ([here](https://github.com/edoren/SkinChanger/blob/fb63f40630a4793edcdff4d1675a43e62b20d9e7/src/main/resources/asm/transformers.js#L60-L78) and [here](https://github.com/zlainsama/OfflineSkins/blob/3efebec9aa134df6b87a2affb2342626f87eabf2/src/main/resources/transformers.js#L4-L18)) to return a modified skin, which is exactly the method Chat Heads is using and there is works perfectly fine. Tested OfflineSkins 1.19-v2 with Chat Heads 0.6.2 - just because I had a 1.19 server lying around but it should work on 1.17 upwards as well.
Older versions simply do not have that patch.

Skin Changer hasn't been updated in 2 years and while OfflineSkins is actively developed, they seem to always focus on the latest Minecraft version, so I wouldn't expect them to backport that ASM patch to 1.16 either but if you want, you can try giving them a pretty-please! 😄
