### ISSUE TITLE
Game crashes

### ISSUE THREAD

**Issue by TomerGamerTV** [dzwdz/chat_heads#37]
I have the latest version of the required mods but it still crashes
[latest.log](https://github.com/dzwdz/chat_heads/files/10707794/latest.log)

**Comment by Fourmisain** [comment]
Chat Heads 0.9.0 runs only on Minecraft 1.19.3 or 1.19.1/2 depending on which version you download, but not on 1.19 which you are using.
The last version of Chat Heads for 1.19 was 0.6.0, you can get it [here](https://www.curseforge.com/minecraft/mc-mods/chat-heads/files/3821755).

**Comment by TomerGamerTV** [comment]
> Chat Heads 0.9.0 runs only on Minecraft 1.19.3 or 1.19.1/2 depending on which version you download, but not on 1.19 which you are using. The last version of Chat Heads for 1.19 was 0.6.0, you can get it [here](https://www.curseforge.com/minecraft/mc-mods/chat-heads/files/3821755).

Can you fix the versions in modrinth.com ? this is where i downloaded it from and it says 1.17 in 0.6.0

**Comment by Fourmisain** [comment]
There's multiple 0.6.0 versions, one for 1.16, one for 1.17, one for 1.18 and... Ah!
I remember I intentionally did not upload the 0.6.0 version for 1.19 on Modrinth since 1.19.1/2 was already out for months and I felt there was no reason to support 1.19 anymore.

Sorry for the confusion, I did not expect anyone to be using 1.19 anymore, especially not today.

I'd always recommend updating to the latest (patch) version of Minecraft, since they often contain critical bug fixes.
It takes some work but that's where most mods are updated on, especially for Fabric.
If you're still using 1.19 because you're worrying about chat reports in later versions, I highly recommend getting [No Chat Reports](https://modrinth.com/mod/no-chat-reports).
For Paper/Bukkit/Spiggot servers there's also e.g. [FreedomChat](https://modrinth.com/plugin/freedomchat/versions).

**Comment by TomerGamerTV** [comment]
> There's multiple 0.6.0 versions, one for 1.16, one for 1.17, one for 1.18 and... Ah!
> 
> I remember I intentionally did not upload the 0.6.0 version for 1.19 on Modrinth since 1.19.1/2 was already out for months and I felt there was no reason to support 1.19 anymore.
> 
> 
> 
> Sorry for the confusion, I did not expect anyone to be using 1.19 anymore, especially not today.
> 
> 
> 
> I'd always recommend updating to the latest (patch) version of Minecraft, since they often contain critical bug fixes.
> 
> It takes some work but that's where most mods are updated on, especially for Fabric.
> 
> If you're still using 1.19 because you're worrying about chat reports in later versions, I highly recommend getting [No Chat Reports](https://modrinth.com/mod/no-chat-reports).
> 
> For Paper/Bukkit/Spiggot servers there's also e.g. [FreedomChat](https://modrinth.com/plugin/freedomchat/versions).

I usually prefer to not install additional mods like that then there is no new stuff but ok
