### ISSUE TITLE
Chat Tab completion

### ISSUE THREAD

**Issue by JustAlittleWolf** [dzwdz/chat_heads#47]
Player heads are cut off when trying to use tab completion and the cursor is to the left of the screen

![image](https://user-images.githubusercontent.com/54244277/233741650-4ce4bb58-953c-4c59-8c14-0b9a28d52516.png)

**Comment by Fourmisain** [comment]
Ah, yeah, that's kind of sort of intentional, since moving the completions means the text isn't aligned anymore (and it would require a bunch of unreadable code).

I guess the completions should still be moved in this specific case - better than hiding the icons I suppose?
Not sure when I come around to this, things have been going slow lately.

**Comment by Fourmisain** [comment]
I lied.
![fixed](https://user-images.githubusercontent.com/8464472/233777174-33cb0c7c-d7cd-41ab-b402-e8c3bf34328c.png)
(Found a way that doesn't require tons of bad code.)

New versions for 1.19.4 and 1.19.2 are up!

**Comment by JustAlittleWolf** [comment]
awesome, thank you so much!
