### ISSUE TITLE
Heads don't appear with chat delay

### ISSUE THREAD

**Issue by Treetrain1** [dzwdz/chat_heads#48]
Chat delay is an accessibility option.
When chat delay is on, the heads only appear when you send one message.
Pending messages do not have the heads.

The pending messages do have heads if you send a new message before it appears, then they don't appear again

In this screenshot, I sent "a" twice, waited for a pending message to pass, entered a new message, and then waited. The last "a" is the message that I entered after waiting.
![image](https://user-images.githubusercontent.com/39657565/233811801-d752eb0f-90db-410b-99c4-dff15a095288.png)

**Comment by Fourmisain** [comment]
This looked pretty hard at first, but I think I managed to fix it!

The issue was that Chat Heads remembered the sender the second it received a message and used what it remembered when it finally displayed the message, so when a message is delayed it could use the wrong sender and since Chat Heads also intentionally forgets the sender, this would show up like it did here.

I was just trying to backport the fix to 1.19.2 and as it turns out this bug was only introduced in 1.19.4 due to the way sender info was passed - less release work for me!

Aight, new versions are up!

P.S.
It looks like No Chat Reports currently doesn't work with chat delays, so just a heads-up on that
