### ISSUE TITLE
Skin caching/fetching for offline players?

### ISSUE THREAD

**Issue by LadyHaley** [dzwdz/chat_heads#53]
One examples is I have some leaderboards sent in chat that uses player name placeholders 
![image](https://github.com/dzwdz/chat_heads/assets/3754909/9b8afb76-539e-42b6-8a12-4a73434c3d67)
When they are online their skin will show up there, but not when they are offline, is there a way to cache or fetch missing skins for when the player isnt online?

**Comment by Fourmisain** [comment]
Hm... the thing is that this behavior isn't actually intended, as in: Chat Heads isn't supposed to add heads to non-player messages.
What you see here is a side effect of heuristics (mis-)matching a message due to containing a player name.

While this looks fine in this case, I'm not sure if it's a good idea to lean into this idea.

The heads are meant to easily tell "who you are chatting with", basically saying "this player just sent a message!"

Heads for offline players would somewhat defeat that purpose.
I could potentially see it if the heads were grayed out or something, but that is a lot of work for something that is essentially a bug, so I really don't know...
