### ISSUE TITLE
Not working on 1.20.1

### ISSUE THREAD

**Issue by MsFragment9996** [dzwdz/chat_heads#55]
I used "Chat Heads" before on version 1.19.2 on Fabric (with OptiFabric and Optifine) and everything worked. Now I tried on 1.20.1 in the same way and I see the head icons only in TAB. Besides everything I tried to change in the settings using the Mod Menu, nothing seems to work. I even downloaded the Cloth Config and... I don't see any results. It worked before even with the Chat Patches mod.

![2023-07-14_02 03 11](https://github.com/dzwdz/chat_heads/assets/56838205/ddcf35e3-b6e0-45ab-956d-6cc0665b278b)

Using Fabric on 1.20.1 with Optifine 
The Chat Heads mod is 0.10.16 
Cloth Config is 11.1.106

**Comment by KruASe76** [comment]
for me it doesn't even load on 1.20.1, showing ![this error](https://github.com/dzwdz/chat_heads/assets/55000336/06e065b6-f3b3-45c3-8250-f10613421ae3)

**Comment by Fourmisain** [comment]
As with #54, Optifine is not supported.
We can't do anything about it since it is closed source, doesn't matter if it worked before.
Use Sodium and co instead. Here's a good [list of open source alternatives](https://fabricmc.net/wiki/optifine-alternatives).

I did just test Chat Patches on 1.20 and it seems to work fine with Chat Heads, so it's definitely Optifine.

---

Also, @KruASe76 you're not using the right Chat Heads version. You have a 1.19 version when you need the 1.20 version.
