### ISSUE TITLE
trouble with skin

### ISSUE THREAD

**Issue by Wonkiest29** [dzwdz/chat_heads#56]
we using custom skins and when some body sets hd skin we have that
![image](https://github.com/dzwdz/chat_heads/assets/88631273/aff3f8ed-c7e6-428e-b50f-38e9abfd1542)
but in version 1.19.2 work all normall fix pls

**Comment by Fourmisain** [comment]
I assume you're using [CustomSkinLoader](https://www.curseforge.com/minecraft/mc-mods/customskinloader)? Though it probably doesn't matter how the skins are loaded.

Just tested it and HD skins do surprisingly work on 0.9.0 but broke in 0.10.0 due to layer blending.

Was surprised HD skins worked at all since Chat Heads has always assumed vanilla sizes. I think it's because the offsets aren't really pixel offsets but offsets in UV space, so with HD skins there's simply more "pixels per pixel", so to speak.
The same isn't true for layer blending as that directly works on pixels, hence it grabs the wrong ones, and too few as well.

Anyway, I think I just managed to fix it, so I'll do another round of releases soon.

**Comment by Fourmisain** [comment]
Aight, new versions are up, let me know if there's still any issue.

**Comment by Wonkiest29** [comment]
Thanks for answering, My community says thanks.
Ps: we have launcher with custom authlib
(authentication servers)  and it getting from url
THANKS

**Comment by Wonkiest29** [comment]
Does i need build?

**Comment by Fourmisain** [comment]
Sorry, there's been a crash issue #57 with my fix (due to loading cape textures).

I unpublished the new version, I'll hopefully release a fixed fixed version soon.

**Comment by Fourmisain** [comment]
The crash has been fixed, you can get the latest version 0.10.18 on [Modrinth](https://modrinth.com/mod/chat-heads/versions) (or [CurseForge](https://www.curseforge.com/minecraft/mc-mods/chat-heads/files), once the files have been approved).
