### ISSUE TITLE
Add "heads" to server messages & Grayscale to whispers.

### ISSUE THREAD

**Issue by Kriislol** [dzwdz/chat_heads#61]
My suggestion is to have a robot/microphone head added to server messages, and add a grayscale filter to heads when whispering to a player.

**Comment by Fourmisain** [comment]
> My suggestion is to have a robot/microphone head added to server messages

Hm... I don't really see an upside to that idea, because your eyes are naturally drawn towards the heads / icons.
Putting a head or icon on every single message would just make it harder to see the actual player chat messages in a sea of unrelated server messages.
The icon wouldn't have any meaning and I also don't think that it would look any better.

Vanilla also already has a server message indicator, the grey bar in front of the message - though admittedly this thing is useless on most servers, since they strip the cryptographic signatures of player messages and turn them all into server messages.

We could maybe try to remove that bar for player messages, so only "non-chat server messages" have it, though I can already see the incompatibilities with other chat mods that this would cause...

> add a grayscale filter to heads when whispering to a player.

Grayscale to me implies offline or afk. (And there was a request to support messages for offline players.)
Grayscale heads are also harder to distinguish, e.g. when whispering with multiple players or when another player has a naturally gray skin.
While this could theoretically boost visiblity of whispers, whispers already are highly visible due to their different chat color and use of italics.
So yeah, not really seeing that one either...
