### ISSUE TITLE
Crash on Fabric 1.20.1 with Clean Chat + Incompatibility with Origin Realms server

### ISSUE THREAD

**Issue by Deemitry88** [dzwdz/chat_heads#74]
It just crashs whenever I just start the game
https://mclo.gs/BqgRd0k

**Comment by Deemitry88** [comment]
Found the problem ! The mod is not compatible with clean chat because it changes the same thing I think

[Render thread/WARN]: @ModifyConstant conflict. Skipping chat_heads.mixins.json:ChatComponentMixin from mod chat_heads->@ModifyConstant::chatheads$moveTagIcon(I)I with priority 990, already redirected by cleanchat.mixins.json:ChatComponentMixin from mod cleanchat->@ModifyConstant::moveIcon(I)I with priority 1000

**Comment by Fourmisain** [comment]
Ah you found it already, I was just typing! 😄

As you said, it's a conflict with [CleanChat](https://modrinth.com/mod/cleanchat). We both want to [move the tag icon](https://github.com/DrexHD/CleanChat/blob/e8cf6f96eedaf37dd374e25d893c686457df6b9a/src/main/java/me/drex/cleanchat/mixin/ChatComponentMixin.java#L33C1-L36C6) but only one `@ModifyConstant` can apply.

This looks like a job for MixinExtras, though it probably requires changes on both sides - I'll see if I can fix/PR something tomorrow.

**Comment by Deemitry88** [comment]
anyway chat heads doesn't work on origin realms (even tho I can see the head for a fraction of a second it disappears) idk if you can do something about this but I would be still good if you fix it if I need it for another thing

**Comment by Fourmisain** [comment]
Is it only on Origin Realms? If so, that's weird, as it's a vanilla-compatible server I think, so it shouldn't really be different to any other server.

What you are describing definitely sounds like a mod conflict though.
Looking in you modlist, the mod [ChatAnimation](https://modrinth.com/mod/chatanimation) sounds like it could cause such issues and looking at the code, I think I have some idea of why. Try removing that mod and see if that fixes it.

**Comment by Deemitry88** [comment]
nah it is still isn't working
![image](https://github.com/dzwdz/chat_heads/assets/91915462/6b525d78-2380-4693-b323-aa2edcd2ed08)

**Comment by Fourmisain** [comment]
Looks like I need to check out Origin Realms some time.

**Comment by Deemitry88** [comment]
If you want to know, Origin realms (as you can see) uses another system to send message in chat (not the vanilla one) and I think the "Player" tag is interfering with the mod, the weird thing is that I saw the head for a fraction of a second so it should be compatible 🤔

**Comment by Fourmisain** [comment]
Released a new version which fixes the compatibility issue with Clean Chat on our side - it might still require the pull request for both to work without issue though.

Also, I did just join Origin Realms using only Chat Heads for a test and the chat heads seem to work just fine:
![test](https://github.com/dzwdz/chat_heads/assets/8464472/fe42478b-5891-4a7a-98d5-6ed5b02a7b8b)
(I didn't try to chat, but chat from others did have heads.)

It's surely a compatibility issue with one of the 277 other mods, but I can't tell which one.
A few chat related candidates that spring out are chatanimation, cleanchat (well we had that), compact-chat, dcch, emojitype....
I did try it again with those but still couldn't replicate the issue.

It might be easier if you try to systematically find the mod causing the issue:
Half your mods, check if the issue is gone.
If it is: It's one of the mods in the disabled half.
If it isn't: It's one of the mods in the enabled half.
Now use the "broken" half, then repeat the steps, halfing again and again, geting closer and closer to the mod causing the issues.

If the mod list is small enough I can go through and check them.

**Comment by Deemitry88** [comment]
so

**Comment by Deemitry88** [comment]
so the problem was comming from slyde (wich is a mod that aims to do this : 
![image](https://github.com/dzwdz/chat_heads/assets/91915462/6433c344-04e1-4914-841f-02aee0c69e7e)
 on every slider)
 and I guess my chat sliders were not like it should be but by removeing the mod and putting it again it reset and I don't have any problem anymore

**Comment by Fourmisain** [comment]
How weird!
Glad you found the issue, and even better it's not a mod compatibility issue! (Well, besides Compact Chat)

**Comment by Deemitry88** [comment]
so do you think you could fix the glitch with compact chat ?

**Comment by Fourmisain** [comment]
I'm debugging as we speak.

And I think I just found the cause, CompactChat [changed their mixin priority](https://github.com/caoimhebyrne/compact-chat/commit/e1438a33ea781cd9b09ee62386034874da103244#diff-6b4871e0e4e489131a7ca18a925aaad946f11fd9f08cc5923d3cb93f1ebe7a8cR25), easy fix, let's try.

...

It works! Guess another release is due.

**Comment by Fourmisain** [comment]
There we go!
I've only published a 1.20(.1) version, since Compact Chat isn't yet compatible with newer versions.

**Comment by Fourmisain** [comment]
P.S.
The Clean Chat PR was just accepted, so I'd expect a new version soon.

**Comment by Deemitry88** [comment]
Yeah I just saw Clean Chat being updated, thanks very much for all your attention !
