### ISSUE TITLE
Chat heads doesn't seems to work with accents

### ISSUE THREAD

**Issue by mortebrume** [dzwdz/chat_heads#88]
Hi !

On my multiplayer server, some people use nicknames with accents, and chat head doesn't seems to work with this, strangely.
The server doesn't send UUIDs so this is based on the heuristic detection of chatheads. I tried to use name aliases as a temporary solution, but this doesn't work (and I confirmed that the name aliases are working if I'm using a nickname without accents).

I will give you some screens, there's nothing in the logs sadly, so I cannot pinpoint the issue.

(we are using a custom chat plugin, perhaps we could try to modify the plugin so that it could send the real UUIDs so chat heads doesn't have to use heuristic detection ?)

Thank you !

![image](https://github.com/dzwdz/chat_heads/assets/32543196/92b28685-0131-4bb7-8193-efe53718dd14)

**Comment by Fourmisain** [comment]
Ah yeah, accents are filtered out since they are not allowed inside profile names and the fallback heuristic is pretty stupid. It simply compares every "word" in the message with each profile or display name, where a "word" contains only valid characters, so it'd check for the name "Morg" and the name "n" instead of "Morgán".
It's the same as with spaces in the names, I really need to rewrite the display name matching...

> we are using a custom chat plugin, perhaps we could try to modify the plugin so that it could send the real UUIDs so chat heads doesn't have to use heuristic detection ?

It would be enough if you add a click event with an appropriate `/tell` command - you know the one where you can DM a player by clicking on their name in chat? That's the first heuristic Chat Heads uses and by far the best, as it uses the player's profile name.
(Plus it's convenient for your players as well.)

**Comment by Fourmisain** [comment]
I uploaded a (completely untested) [test version](https://github.com/dzwdz/chat_heads/releases/tag/new-heuristic-test) for Fabric 1.20.5/6, which should have this fixed if you wanna try it out.

**Comment by Fourmisain** [comment]
After way too many backports, 0.12.0 is out!
Lemme know if there's still any issues.
