### ISSUE TITLE
MCCI server chat messages not showing at all

### ISSUE THREAD

**Issue by SPINZ1** [dzwdz/chat_heads#90]
When "handle system messages" is enabled, messages sent from the server including modified player messages don't appear in chat.
https://mclo.gs/TtqDV7Y

**Comment by Fourmisain** [comment]
> StringIndexOutOfBoundsException: index 0, length 0

Empty names?
Every time I think "that's impossible and will never happen" a server comes around and proves otherwise... 😅
Maybe the server has some fake player system, as is often used by mods for mob spawning chunk loaders, automated miners etc?

I'll just add guards everywhere.

...

Aight, a million backports are done and 0.12.1 is out!
(Also, aliases can use spaces now too.)

Lemme know if there's still any issues.
